language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
  - cargo install cargo-with
script:
  - cargo clippy --tests
  - cargo build
  - cargo test
  - cargo doc
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: bionic # for JDK
addons:
  apt:
    packages:
      - openjdk-11-jdk-headless
