language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: xenial # for JDK
addons:
  apt:
    packages:
      - default-jdk-headless
